### ISSUE TITLE
FacebookBox: Wrong language

### ISSUE THREAD

**Issue by JanaME** [palasthotel/grid-wordpress-box-social#1]
There’s a problem with the new Facebook Likebox which can be seen e.g. here: http://www.my-entdecker.de

Language de is chosen but unfortunately the box is rendered with language en.

**Comment by EdwardBock** [comment]
@JanaME 
Is fixed and update is on wordpress.org

**Comment by EdwardBock** [comment]
@JanaME 
You close it if it works :)

**Comment by JanaME** [comment]
Still not working. I choose "de" in the settings, but it's rendered the as the following:

```
<div class="fb-like-box fb_iframe_widget" data-href="https://www.facebook.com/my.entdecker" data-colorscheme="light" data-show-faces="true" data-header="true" data-stream="false" data-show-border="true" fb-xfbml-state="rendered" fb-iframe-plugin-query="app_id=&amp;color_scheme=light&amp;container_width=300&amp;header=true&amp;href=https%3A%2F%2Fwww.facebook.com%2Fmy.entdecker&amp;locale=en_US&amp;sdk=joey&amp;show_border=true&amp;show_faces=true&amp;stream=false"> … 
```

**Comment by EdwardBock** [comment]
@JanaME There is nothing wrong with the grid box but myendecker loads the JS for facebook at another location too. That location is before the grid box the the US facebook script version is already loaded. That's why it's english.
Let's have a look at this together when you are at work.
